<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>comment</key>
    <string>MuPAD code -- christopher.creutzig@mathworks.com, based on Pascal mode by chris@cjack.com.</string>
    <key>fileTypes</key>
    <array>
      <string>mu</string>
      <string>tst</string>
    </array>
    <key>foldingStartMarker</key>
    <string>\b(proc|domain|case|if|%if|for|while|repeat)\b</string>
    <key>foldingStopMarker</key>
    <string>\b(end|end_proc|end_domain|end_case|end_if|end_for|end_while|end_repeat)\b</string>
    <key>name</key>
    <string>MuPAD</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>begin</key>
        <string>//</string>
        <key>end</key>
        <string>$</string>
        <key>name</key>
        <string>comment.line.double-slash.mupad</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>text.plain</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>include</key>
        <string>#blockcomment</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(axiom|end_axiom|category|end_category|begin|break|case|do|downto|elif|else|end_case|end_for|end_if|end_proc|end_repeat|end_while|for|from|if|%if|local|name|next|of|option|otherwise|proc|quit|repeat|save|step|then|to|until|while|domain|end|inherits|end_domain)\b</string>
        <key>name</key>
        <string>keyword.control.mupad</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(intersect|minus|union)\b|-&gt;|--&gt;|\.</string>
        <key>name</key>
        <string>keyword.operator.mupad</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(div|mod)\b|\+|-|\*|/|\^|\|</string>
        <key>name</key>
        <string>keyword.operator.arithmetic.mupad</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(and|in|not|or|xor)\b|&gt;|&lt;|&lt;&gt;|=|&lt;=&gt;|&lt;==|==&gt;|\|\||&amp;&amp;</string>
        <key>name</key>
        <string>keyword.operator.logical.mupad</string>
      </dict>
      <dict>
        <key>match</key>
        <string>:=</string>
        <key>name</key>
        <string>keyword.operator.assignment.mupad</string>
      </dict>
      <dict>
        <key>match</key>
        <string>::</string>
        <key>name</key>
        <string>punctuation.accessor.mupad</string>
      </dict>
      <dict>
        <key>match</key>
        <string>;</string>
        <key>name</key>
        <string>punctuation.terminator.mupad</string>
      </dict>
      <dict>
        <key>match</key>
        <string>,</string>
        <key>name</key>
        <string>punctuation.separator.mupad</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(E|FAIL|FALSE|I|NIL|TRUE|UNKNOWN|PI|EULER|CATALAN|infinity|undefined)\b</string>
        <key>name</key>
        <string>constant.language.mupad</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(\b[a-zA-Z_#]\w*\b|`.*?`)</string>
        <key>name</key>
        <string>entity.name.variable.mupad</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.mupad</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.mupad</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(?:\b([a-zA-Z_]w+(?:::\w+)*|`.*?`)\s*:=\s*)\bproc\b\s*\((.*?)\)</string>
        <key>name</key>
        <string>declaration.function.mupad.one</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.mupad</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.mupad</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(?:\b([a-zA-Z_]w+(?:::\w+)*|`.*?`)\s*:=\s*)\s*\((.*?)\)\s*--?&gt;</string>
        <key>name</key>
        <string>declaration.function.mupad.two</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.mupad</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.mupad</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(?:\b([a-zA-Z_]w+(?:::\w+)*|`.*?`)\s*:=\s*)\s*(\w+)\s*--?&gt;</string>
        <key>name</key>
        <string>declaration.function.mupad.three</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(([0-9]+\.?[0-9]*)((e|E)(\+|-)?[0-9]+)?)\b</string>
        <key>name</key>
        <string>constant.numeric.mupad</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>&quot;</string>
        <key>end</key>
        <string>&quot;</string>
        <key>name</key>
        <string>string.quoted.double.mupad</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string_escaped_char</string>
          </dict>
        </array>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>blockcomment</key>
      <dict>
        <key>begin</key>
        <string>/\*</string>
        <key>end</key>
        <string>\*/</string>
        <key>name</key>
        <string>comment.block.mupad</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#blockcomment</string>
          </dict>
        </array>
      </dict>
      <key>string_escaped_char</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\(\\|[bntr&quot;])</string>
            <key>name</key>
            <string>constant.character.escape.mupad</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>invalid.illegal.unknown-escape.mupad</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.mupad</string>
    <key>uuid</key>
    <string>341D8B40-5DAB-476A-B0CD-90D87D735E33</string>
  </dict>
</plist>
